config/routes.rb
Myapp::Application.routes.draw do
  resources :category_masters

  resources :posts
  resources :university
  resources :college
  resources :posts do
    resources :comments
  end
  root :to => "home#index"

end

app/models/category_master.rb
class CategoryMaster < ActiveRecord::Base
end

app/models/college.rb
class College < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
  has_many :comments
end

app/models/university.rb
class University < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/category_masters_controller.rb
class CategoryMastersController < ApplicationController
  # GET /category_masters
  # GET /category_masters.xml
  def index
    @category_masters = CategoryMaster.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @category_masters }
    end
  end

  # GET /category_masters/1
  # GET /category_masters/1.xml
  def show
    @category_master = CategoryMaster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category_master }
    end
  end

  # GET /category_masters/new
  # GET /category_masters/new.xml
  def new
    @category_master = CategoryMaster.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category_master }
    end
  end

  # GET /category_masters/1/edit
  def edit
    @category_master = CategoryMaster.find(params[:id])
  end

  # POST /category_masters
  # POST /category_masters.xml
  def create
    @category_master = CategoryMaster.new(params[:category_master])

    respond_to do |format|
      if @category_master.save
        format.html { redirect_to(@category_master, :notice => 'Category master was successfully created.') }
        format.xml  { render :xml => @category_master, :status => :created, :location => @category_master }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category_master.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /category_masters/1
  # PUT /category_masters/1.xml
  def update
    @category_master = CategoryMaster.find(params[:id])

    respond_to do |format|
      if @category_master.update_attributes(params[:category_master])
        format.html { redirect_to(@category_master, :notice => 'Category master was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category_master.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /category_masters/1
  # DELETE /category_masters/1.xml
  def destroy
    @category_master = CategoryMaster.find(params[:id])
    @category_master.destroy

    respond_to do |format|
      format.html { redirect_to(category_masters_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_masters_helper.rb
module CategoryMastersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/category_masters/_form.html.erb
<%= form_for(@category_master) do |f| %>
  <% if @category_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category_master.errors.count, "error") %> prohibited this category_master from being saved:</h2>

      <ul>
      <% @category_master.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :isActive %><br />
    <%= f.text_field :isActive %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/category_masters/edit.html.erb
<h1>Editing category_master</h1>

<%= render 'form' %>

<%= link_to 'Show', @category_master %> |
<%= link_to 'Back', category_masters_path %>

app/views/category_masters/index.html.erb
<h1>Listing category_masters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Isactive</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @category_masters.each do |category_master| %>
  <tr>
    <td><%= category_master.name %></td>
    <td><%= category_master.description %></td>
    <td><%= category_master.isActive %></td>
    <td><%= link_to 'Show', category_master %></td>
    <td><%= link_to 'Edit', edit_category_master_path(category_master) %></td>
    <td><%= link_to 'Destroy', category_master, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category master', new_category_master_path %>

app/views/category_masters/new.html.erb
<h1>New category_master</h1>

<%= render 'form' %>

<%= link_to 'Back', category_masters_path %>

app/views/category_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category_master.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category_master.description %>
</p>

<p>
  <b>Isactive:</b>
  <%= @category_master.isActive %>
</p>


<%= link_to 'Edit', edit_category_master_path(@category_master) %> |
<%= link_to 'Back', category_masters_path %>

app/views/home/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;.
charset=iso-8859-1" />
<meta http-equiv="Content-Language" content="en-us" />
<title>CareerDisk.com</title>
<%= stylesheet_link_tag "newstyle.css" %>



</head>
<body id="library">
<div id="container">
<div id="header">
<h1>careerdisk</h1>

</div>
<div id="content">
<%= link_to "My Blog", posts_path %>
<%= yield -%>
</div>
<div id="sidebar"></div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>